# =============================
# railway.toml
# =============================

[build]
command = "pip install -r requirements.txt"

[deploy]
command = "python main.py"

[cron]
# Runs every 15 minutes (UTC)
schedule = "*/15 * * * *"
command = "python main.py"
